gambitproject/gambit

- library/src/file.cc
The current condition will always be false (`c` can't be equal to both `'+'` and `'-'`). It seems pretty clear that the following was intended.
Thanks for your time,
Michael McConville
University of Utah
> Fix error condition in integer parser

- .github/workflows/ci.yml
Creates an initial CI configuration with GitHub Actions that builds gambit on each push, pull request and once a month for Ubuntu and macOS.
GitHub Actions can be enabled for the gambit repository here: https://github.com/gambitproject/gambit/actions.
In the mean time an example run with this configuration can be found [on my fork](https://github.com/EwoutH/gambit/actions/runs/1687685824).
-----
The Linux (Ubuntu) build unfortunately currently fails:
```
/usr/bin/ld: src/solvers/gtracer/aggame.o: in function `Gambit::gametracer::aggame::SymPayoffMatrix(Gambit::gametracer::cmatrix&, Gambit::gametracer::cvector&, double)':
/home/runner/work/gambit/gambit/src/solvers/gtracer/aggame.cc:403: undefined reference to `Gambit::agg::AGG::doProjection(int, int, double*)'
collect2: error: ld returned …
```
> Create initial CI configuration with GitHub actions

- .github/workflows/python.yml
The `3.10` is currently interpreted as a number, and thus Python 3.1 is used. Changing it to `'3.10'` as a string fixes this.
> CI: Use Python 3.10 instead of 3.1

- src/setup.py
A small addition to `setup.py`, in which the `project_urls` property is defined with links to the documentation, source code and issue tracker.
This allows PyPI to display direct links to the documentation, source code and issue tracker.
See https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls
> setup.py: Add project URLs for documentation, source code and issues

- .github/workflows/lint.yml
- .github/workflows/python.yml
- .github/workflows/tools.yml
- .github/workflows/wheels.yml
Update the checkout, setup-python, upload-artifact and download-artifact actions to v3
> CI: Update used actions to v3

- doc/api.rst
- doc/pyapi.rst
- doc/tools.rst
- src/pygambit/gambit.pxd
- src/pygambit/nash.h
- src/pygambit/nash.pxi
- src/pygambit/nash.py
- src/pygambit/tests/test_games/poker.efg
- src/pygambit/tests/test_nash.py
- src/pygambit/util.h
- src/solvers/enummixed/enummixed.h
- src/solvers/enumpure/enumpure.h
- src/solvers/gnm/gnm.h
- src/solvers/ipa/ipa.h
- src/solvers/lcp/lcp.h
- src/solvers/liap/liap.h
- src/solvers/simpdiv/simpdiv.h
- src/tools/lp/efglp.h
- src/tools/lp/nfglp.h
* In Python/Cython, this removes the cumbersome class-based algorithm interfaces in favour of simpler function-based ones.
* Simple function interfaces have been added to C++ as well.
* Memory handling for QRE results has been converted to shared_ptr.
* Adds test suite for calls to Nash-finding methods - these are intended simply to ensure that a call to the method works in principle, and are not a complete test suite for individual methods.
* Calls to the external command-line tools are now deprecated.
* The documentation has been updated to remove references to the external tools and to list the methods available in pygambit.nash.
> Simplify the calling and implementation of Nash-finding algorithms

- src/games/game.cc
- src/games/game.h
- src/games/gametable.h
- src/games/mixed.h
- src/games/mixed.imp
- src/games/stratspt.cc
- src/games/stratspt.h
This removes obsolete and unused code in the C++ game library for representing the concept of a "restriction" of a game.  We have decided there are much better ways of accomplishing what the concept aimed to do.
> Remove obsolete game restriction support in C++

- doc/pygambit.user.rst
- src/games/game.h
- src/pygambit/gambit.pxd
- src/pygambit/game.pxi
- src/pygambit/outcome.pxi
- src/pygambit/tests/test_extensive_outcomes.py
- src/pygambit/tests/test_game.py
- src/pygambit/tests/test_outcomes.py
This changes the method for accessing outcome payoffs in pygambit from integer indices to player references (either instances of Player, or label strings). This aligns with the conventions used elsewhere in the package.
Alongside this, the user guide has been revised to focus on .from_arrays as the most natural quick-start way to create a new game in strategic form.
> In pygambit, access outcome payoffs only by player reference.

- ChangeLog
- src/pygambit/behav.pxi
- src/pygambit/tests/test_behav.py
I have implemented the discussed changes and believe the code in the final commit is good to be merged now; happy to rebase if you suggest that, and to a changelog entry, but would need some guidance on the latter..
> 351 bug check for chance information sets in mixed behavior profiles

- ChangeLog
- doc/pygambit.api.rst
- src/pygambit/gambit.pxd
- src/pygambit/game.pxi
- src/pygambit/player.pxi
- src/pygambit/tests/test_players.py
* Moves `Player.strategies.add()` to `Game.add_strategy()`, with the old call deprecated, to be removed in 16.2.
* Implements `Game.delete_strategy()` to remove a strategy from a strategic game.
> Revises methods to change strategies for a player:

- ChangeLog
- doc/pygambit.api.rst
- src/games/behav.h
- src/games/behav.imp
- src/games/mixed.h
- src/games/mixed.imp
- src/pygambit/behav.pxi
- src/pygambit/gambit.pxd
- src/pygambit/mixed.pxi
- src/pygambit/tests/test_behav.py
- src/pygambit/tests/test_mixed.py
* Implement regret calculation for mixed strategy profiles; this had been omitted previously in both C++ and Python.
* Correct implementation of regret for mixed behavior profiles; this was computing something non-standard (a non-conditional expected payoff loss relative to the actual agent strategy, and not the best response)
Closes #352.
> Implement regret for mixed strategy and behavior profiles.

- ChangeLog
- src/games/gametree.cc
- src/games/gametree.h
- src/pygambit/behav.pxi
- src/pygambit/game.pxi
- src/pygambit/tests/test_actions.py
- src/pygambit/tests/test_games/chance_root_3_moves_only_one_nonzero_prob.efg
- src/pygambit/tests/test_games/chance_root_5_moves_no_nonterm_player_nodes.efg
This is now a single commit with a ChangeLog entry, and is so ready for review and possible merging
> 372 bug chance action probabilities after deleting chance action

- src/pygambit/gambit.pxd
- src/pygambit/tests/test_game.py
Since it wasn't clear to me why some additions of "except +" would break compilation, I choose to try except absolutely everywhere -- the only cases now where we don't have it is where having it breaks compilation (in which case it is there but commented out, with the extra comment "doesn't compile").
The new tests are only for cases where I managed to trigger these exceptions, which are all variants of the example from 389, using payoff or liap value.
Let me know what you suggest to push, but I thought you'd want to see which ones were breaking compilation anyway.
> except + for all functions in gambit.pxd unless it breaks compilation

- ChangeLog
- doc/biblio.rst
- doc/pygambit.api.rst
- doc/pygambit.user.rst
- src/pygambit/qre.py
QRE estimation was (quietly) added in 16.1.0.  This does the following:
1.  Updates the implementation of both fixed-point and empirical methods to fix bugs in accessing mixed strategy profiles.
2.  Adds improved docstrings to the methods (and the result class), and a user guide section to the documentation with a very brief exposition of their use.
> Document quantal response estimation in pygambit.

- ChangeLog
- src/solvers/lp/efglp.cc
This corrects a bug in formulating the LP tableau for the sequence form. Specifically, there was a missing parenthesis in setting tableau entries; the effect of this is that the tableau was incorrect in the case of a game which had a chance node that was not the root node.
This closes #134
> Fix bug in formulating LP tableau for sequence form.

- src/core/array.h
- src/games/behavmixed.imp
- src/games/behavpure.cc
- src/games/behavspt.h
- src/games/game.cc
- src/games/game.h
- src/games/gametree.cc
- src/games/gametree.h
- src/games/nash.cc
- src/games/stratpure.cc
- src/games/stratspt.h
- src/gui/efglayout.cc
- src/solvers/lcp/efglcp.cc
- src/solvers/lp/efglp.cc
This implements a standard convention for accessing collections of game elements. Where appropriate, this provides GetXXXs() functions which, at present, return Arrays of the corresponding GameObjectPtr.
Similar functions are provided for support profiles.
With these changes, iterator-type access for game members is now possible consistently across using code, and this is preferred style.
> Standardise interfaces for collections in game representation.

- ChangeLog
- doc/pygambit.api.rst
- doc/pygambit.user.rst
- src/pygambit/nash.py
- src/pyproject.toml
- tests/test_nash.py
This provides an implementation of NashComputationResult, a class which represents the outcome of a method for computing Nash equilibria.
All equilibrium-computing methods have been changed to return an object of this class instead of a bare list of profiles.
> Implement object to return from Nash equilibrium computation algorithms.

- ChangeLog
- doc/pygambit.api.rst
- doc/pygambit.user.rst
- src/pygambit/behav.pxi
- src/pygambit/gambit.pyx
- src/pygambit/game.pxi
- src/pygambit/infoset.pxi
- src/pygambit/mixed.pxi
- src/pygambit/node.pxi
- src/pygambit/player.pxi
- src/pygambit/stratspt.pxi
- src/pygambit/tests/test_game_resolve_functions.py
- src/pygambit/tests/test_outcomes.py
- src/pygambit/tests/test_players.py
* In the case where multiple game objects in the same scope (actions, strategies, etc.) had the same label, indexing on collections by label was silently returning the first match. This changes indexing to match conventions used elsewhere in label resolution, and further raises an exception on multiple matches.
* Failing to match on a string index raises a KeyError instead of an IndexError; this is more Pythonic.
> Refine implementation of label indexing on game collection objects.

- ChangeLog
- src/pygambit/gambit.pyx
- src/pygambit/game.pxi
- tests/test_node.py
Import a list of valid terminal node references for  the append_move and append_infoset functions. Further, the test_node and test_infosets test function have been modified to check the newly acquired functionality.
> Import a list of valid terminal node references.

- src/games/game.h
- src/games/gameagg.h
- src/games/gamebagg.h
- src/games/gametable.h
- src/games/gametree.cc
- src/games/gametree.h
- src/pygambit/gambit.pxd
- src/pygambit/game.pxi
- tests/test_node.py
Extend `GameTreeRep` to keep track of the total number of non-terminal nodes in the game
Additionally, fixes a bug in `m_numNodes` counter in operations involving delete. 
Solves #503
> Issue 503. Extend `GameTreeRep` to keep track of the total number of non-terminal nodes in the game

- src/games/game.h
- src/games/gametree.cc
> Change `GameInfosetRep::m_actions` and `GameInfosetRep::m_probs` from `Gambit::Array` to `std::vector`

- doc/build.rst
TODO:
- @tturocy @rahulsavani how is this currently done? This would be good to automate - see https://github.com/alan-turing-institute/gambit_admin/issues/2
> Readthedocs build instructions
